{% set data = load_setup_py_data() %}

package:
  name: "pymt_topoflow"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - topoflow 

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - topoflow 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_topoflow
  commands:
    - config_file=$(mmd-stage infil_component . > MANIFEST && mmd-query infil_component --var=run.config_file.path)
    - bmi-test pymt_topoflow.bmi:infil_component --infile=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage infil_component . > MANIFEST && mmd-query infil_component --var=run.config_file.path)
    - bmi-test pymt_topoflow.bmi:infil_component --infile=$config_file --manifest=MANIFEST -v
    - config_file=$(mmd-stage infil_component . > MANIFEST && mmd-query infil_component --var=run.config_file.path)
    - bmi-test pymt_topoflow.bmi:infil_component --infile=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the topoflow BMI.
  home: https://github.com/mcflugen/pymt_topoflow
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_topoflow
