site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: 'site'
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: 'case'
    units: '-'
n_steps:
  description: Number of time steps
  value:
    type: int
    default: 3600
    range:
      min: 1
      max: 3153600000
    units: '-'
dt:
  description: Model time step
  value:
    type: float
    default: 600.0
    range:
      min: 1
      max: 31536000.0
    units: s
pixel_file:
  description: Monitored pixel/grid file (outlets)
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ks_0_ptype:
  description: Saturated hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ks_0_dtype:
  description: Saturated hydraulic conductivity data type
  value:
    type: choice
    default: Scalar
    choices:
    - float
    - int
    - long
    - string
    units: '-'
Ks_0:
  description: Scalar value
  value:
    type: float
    default: 7.2e-06
    range:
      min: 1E-8
      max: 1E-0
Ks_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
Ki_0_ptype:
  description: Initial hydraulic conductivity
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m s-1
Ki_0_dtype:
  description: Initial hydraulic conductivity data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
Ki_0:
  description: Scalar value
  value:
    type: float
    default: 5.0e-07
    range:
      min: 1.0e-08
      max: 1.0
Ki_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qs_0_ptype:
  description: Saturated soil water content
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qs_0_dtype:
  description: Saturated soil water content data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
qs_0:
  description: Scalar value
  value:
    type: float
    default: 0.485
    range:
      min: 0.0
      max: 1.0
qs_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
qi_0_ptype:
  description: Initial soil water content (< theta_sat)
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
qi_0_dtype:
  description: Initial soil water content data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
qi_0:
  description: Scalar value
  value:
    type: float
    default: 0.375
    range:
      min: 0.0
      max: 1.0
qi_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
G_0_ptype:
  description: Capillary length scale
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: m
G_0_dtype:
  description: Capillary length scale data type
  value:
    type: choice
    default: float
    choices:
    - float
    - int
    - long
    - string
    units: '-'
G_0:
  description: Scalar value
  value:
    type: float
    default: 0.725
    range:
      min: 0.0
      max: 1.0
G_0_file:
  description: Grid, time series, or grid sequence file
  value:
    type: file
    default: 'off'
    files:
    - 'off'
soil_type_0:
  description: Closest standard soil type
  value:
    type: choice
    default: Sand
    choices:
    - Sand
    - Loamy Sand
    - Sandy Loam
    - Silty Loam
    - Loam
    - Sandy Clay Loam
    - Silty Clay Loam
    - Clay Loam
    - Sandy Clay
    - Silty Clay
    - Clay
    units: '-'
